frappe.ui.form.on("Lead", "refresh", function(frm) {
cur_frm.set_query("source", function() {
    return {
        filters: [
            ['Lead Source', 'name', 'in', 'Generated By Sales Person,Demo,Customers Visit To Branch,Service Camp,Others,Toll Free Number,Direct - Project Manager,Branch - Project Manager,SELCO Foundation,SKDRDP,Business Associate']
        ]
    }
})
});

frappe.ui.form.on("Lead", "selco_project_enquiry",function(frm) 
{
cur_frm.set_df_property("selco_area", "reqd", true);
})