# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from . import __version__ as app_version

app_name = "selco"
app_title = "SELCO"
app_publisher = "SELCO"
app_description = "Selco Customizations"
app_icon = "octicon octicon-file-directory"
app_color = "grey"
app_email = "basawaraj@selco-india.com"
app_license = "MIT"

doc_events = {
    "Issue": {
         "before_insert":"selco.selco.selco_customizations.selco_issue_before_insert",
         "validate": "selco.selco.selco_customizations.selco_issue_validate1"
    },
    "Warranty Claim": {
          "validate": "selco.selco.selco_customizations.selco_warranty_claim_validate"
    },
    "Material Request": {
           "validate":"selco.selco.selco_customizations.selco_material_request_validate",
           "before_insert":"selco.selco.selco_customizations.selco_material_request_before_insert"
    },
    "Purchase Receipt":{
              "before_insert":"selco.selco.selco_customizations.selco_purchase_receipt_before_insert",
              "validate":"selco.selco.selco_customizations.selco_purchase_receipt_validate"
    },
    "Payment Entry":{
              "before_insert":"selco.selco.selco_customizations.selco_payment_entry_before_insert",
              "validate":"selco.selco.selco_customizations.selco_payment_entry_validate"
    },
      "Lead":{
            "before_insert":"selco.selco.selco_customizations.selco_lead_before_insert",
            "validate":"selco.selco.selco_customizations.selco_lead_validate"

      },
      "Customer":{
            "before_insert":"selco.selco.selco_customizations.selco_customer_before_insert",
            "validate":"selco.selco.selco_customizations.selco_customer_validate"
     },
     "Journal Entry":{
             "before_insert":"selco.selco.selco_customizations.selco_journal_entry_before_insert",
             "validate":"selco.selco.selco_customizations.selco_journal_entry_validate"
     },
     "Delivery Note":{
             "before_insert":"selco.selco.selco_customizations.selco_delivery_note_before_insert",
             "validate":"selco.selco.selco_customizations.selco_delivery_note_validates"
     },
     "Sales Invoice":{
             "before_insert":"selco.selco.selco_customizations.selco_sales_invoice_before_insert",
              "validate":"selco.selco.selco_customizations.selco_sales_invoice_validate"
     },
     "Purchase Invoice":{
             "before_insert":"selco.selco.selco_customizations.selco_purchase_invoice_before_insert",
             "validate":"selco.selco.selco_customizations.selco_purchase_invoice_validate"
     },
     "Stock Entry":{
        "before_insert": "selco.selco.selco_customizations.selco_stock_entry_updates",
         "validate": "selco.selco.selco_customizations.selco_stock_entry_validate",
         "before_save": "selco.selco.selco_customizations.selco_stock_entry_updates",
         "on_submit": "selco.selco.selco_customizations.selco_stock_entry_on_submit_updates",
         "on_cancel": "selco.selco.selco_customizations.selco_stock_entry_on_cancel_updates"
   },
   # "Address":{
   #      "before_insert": "selco.selco.selco_customizations.selco_address_before_insert"
   # },
    "Purchase Order":{
            "before_insert":"selco.selco.selco_customizations.selco_purchase_order_before_insert",
             "validate": "selco.selco.selco_customizations.selco_purchase_order_validate"
  }
 }

# scheduler_events = {
#     "all": [
#         "selco.tasks.all"
#     ],
#     "daily": [
#         "selco.tasks.daily"
#     ],
#     "hourly": [
#         "selco.tasks.hourly"
#     ],
#     "weekly": [
#         "selco.tasks.weekly"
#     ]
#     "monthly": [
#         "selco.tasks.monthly"
#     ]
# }
"""
scheduler_events = {
    "daily": [
        'selco.selco.doctype.selco_customizations.selco_customizations.send_birthday_wishes',
        'selco.selco.doctype.selco_customizations.selco_customizations.send_po_reminder'
    ],
    "hourly": [
        "selco.selco.doctype.selco_customizations.selco_customizations.service_call_info"
    ],
}
"""
# Testing
# -------

# before_tests = "selco.install.before_tests"

# Overriding Whitelisted Methods
# ------------------------------
#
# override_whitelisted_methods = {
#     "frappe.desk.doctype.event.event.get_events": "selco.event.get_events"
# }




# Includes in <head>
# ------------------

# include js, css files in header of desk.html
# app_include_css = "/assets/selco/css/selco.css"
# app_include_js = "/assets/selco/js/selco.js"

# include js, css files in header of web template
# web_include_css = "/assets/selco/css/selco.css"
# web_include_js = "/assets/selco/js/selco.js"

# include js in page
# page_js = {"page" : "public/js/file.js"}

# include js in doctype views
# doctype_js = {"doctype" : "public/js/doctype.js"}
# doctype_list_js = {"doctype" : "public/js/doctype_list.js"}
# doctype_tree_js = {"doctype" : "public/js/doctype_tree.js"}
# doctype_calendar_js = {"doctype" : "public/js/doctype_calendar.js"}

# Home Pages
# ----------

# application home page (will override Website Settings)
# home_page = "login"

# website user home page (by Role)
# role_home_page = {
#	"Role": "home_page"
# }

# Website user home page (by function)
# get_website_user_home_page = "selco.utils.get_home_page"

# Generators
# ----------

# automatically create page for each record of this doctype
# website_generators = ["Web Page"]

# Installation
# ------------

# before_install = "selco.install.before_install"
# after_install = "selco.install.after_install"

# Desk Notifications
# ------------------
# See frappe.core.notifications.get_notification_config

# notification_config = "selco.notifications.get_notification_config"

# Permissions
# -----------
# Permissions evaluated in scripted ways

# permission_query_conditions = {
# 	"Event": "frappe.desk.doctype.event.event.get_permission_query_conditions",
# }
#
# has_permission = {
# 	"Event": "frappe.desk.doctype.event.event.has_permission",
# }

# Document Events
# ---------------
# Hook on document methods and events

# doc_events = {
# 	"*": {
# 		"on_update": "method",
# 		"on_cancel": "method",
# 		"on_trash": "method"
#	}
# }

# Scheduled Tasks
# ---------------

# scheduler_events = {
# 	"all": [
# 		"selco.tasks.all"
# 	],
# 	"daily": [
# 		"selco.tasks.daily"
# 	],
# 	"hourly": [
# 		"selco.tasks.hourly"
# 	],
# 	"weekly": [
# 		"selco.tasks.weekly"
# 	]
# 	"monthly": [
# 		"selco.tasks.monthly"
# 	]
# }

# Testing
# -------

# before_tests = "selco.install.before_tests"

# Overriding Whitelisted Methods
# ------------------------------
#
# override_whitelisted_methods = {
# 	"frappe.desk.doctype.event.event.get_events": "selco.event.get_events"
# }

'''
fixtures = [
  {
    "dt":"Custom Field",
    "filters":[
      ["name", "in", [
      "Stock Entry Detail-hsn_code",
      "Employee-selco_aadhaar_number",
      "Issue-selco_sms_counter_open",
      "Issue-selco_sms_number",
      "Warehouse-selco_warehouse_type",
      "Material Request-selco_logistics_manager_comments",
      "Warehouse-selco_address",
      "Warehouse-selco_state_gstin",
      "Warehouse-selco_cost_center",
      "Warehouse-selco_cb_warehouse_details_1",
      "Warehouse-selco_cst_no",
      "Warehouse-selco_vat_tin_no",
      "Warehouse-selco_godown_email",
      "Warehouse-selco_purchase_invoice_naming_series",
      "Warehouse-selco_grn_naming_series",
      "Warehouse-selco_stock_entry_naming_series",
      "Warehouse-selco_mrn_naming_series",
      "Warehouse-selco_po_naming_series",
      "Warehouse-selco_sb_warehouse_info",
      "Cash Payment Entry-alternative_cost_center",
      "Cash Payment Entry-use_different_cost_center",
      "Journal Entry-selco_branch",
      "Bank Payment-alternative_cost_center",
      "Journal Entry-selco_use_different_cost_center",
      "Journal Entry-selco_alternative_cost_center",
      "Bank Payment-use_different_cost_center",
      "Sales Invoice-selco_branch",
      "Deleted Document-github_sync_id",
      "Task-github_sync_id",
      "Project-github_sync_id",
      "Account-selco_bank_account_type",
      "Account-selco_sales_tax_template",
      "Account-selco_pan_number",
      "Purchase Receipt-selco_type_of_purchase",
      "Warehouse-selco_type",
      "Warehouse-selco_branch",
      "Purchase Order-selco_advance_received_from_customer_",
      "Purchase Order-selco_project_name",
      "Purchase Order-selco_godown",
      "Supplier-selco_type_of_purchase",
      "Branch-selco_purchase_invoice_naming_series",
      "Branch-selco_mrn_naming_series",
      "Branch-selco_po_naming_series",
      "Branch-selco_gstin",
      "Branch-selco_address",
      "Branch-selco_bank_payment_naming_series",
      "Branch-selco_repair_warehouse",
      "Branch-selco_cash_account",
      "Branch-selco_receipt_naming_series",
      "Branch-selco_commission_journal_naming_series",
      "Branch-selco_bank_payment_collection_naming_series",
      "Branch-selco_bill_of_sales_naming_series",
      "Branch-selco_credit_note_naming_series",
      "Branch-selco_contra_naming_series",
      "Branch-selco_service_bill_naming_series",
      "Branch-selco_bank_payment_expenditure_naming_series",
      "Branch-selco_write_off_naming_series",
      "Branch-selco_journal_entry_naming_series",
      "Branch-selco_debit_note__naming_series",
      "Branch-selco_expenditure_account",
      "Branch-selco_collection_account_cash",
      "Branch-selco_collection_account",
      "Branch-selco_cash_payment_naming_series",
      "Branch-selco_sales_invoice_naming_series",
      "Branch-selco_bill_of_material_naming_series",
      "Branch-selco_rejection_out_naming_series",
      "Branch-selco_receipt_note_naming_series",
      "Branch-selco_stock_entry_naming_series",
      "Branch-selco_stock_journal_naming_series",
      "Branch-selco_rejection_in_naming_series",
      "Branch-selco_delivery_note_naming_series",
      "Branch-selco_material_request_naming_series",
      "Branch-selco_customer_complaint_naming_series",
      "Branch-selco_sales_order_naming_series",
      "Branch-selco_opportunity_naming_series",
      "Branch-selco_customer_naming_series",
      "Branch-selco_quotation_naming_series",
      "Branch-selco_lead_naming_series",
      "Branch-selco_address_image_path",
      "Stock Entry-sender_address",
      "Stock Entry-sender_address_link",
      "Stock Entry Detail-reference_rej_in_or_rej_quantity",
      "Stock Entry Detail-reference_rej_in_or_rej_ot",
      "Stock Entry-selco_recipient_address",
      "Stock Entry-selco_recipient_email_id",
      "Stock Entry-selco_recipient_address_link",
      "Stock Entry-selco_destination",
      "Stock Entry-selco_other_references",
      "Stock Entry-selco_nia_no",
      "Stock Entry-selco_e_sugam_date",
      "Stock Entry-selco_e_sugam_number",
      "Stock Entry-selco_stock_journal",
      "Stock Entry-selco_branch_email_id",
      "Stock Entry-selco_get_items_from_rejection_in",
      "Stock Entry-selco_rejection_in_id",
      "Stock Entry-selco_supplier_or_customer_name",
      "Stock Entry-selco_supplier_or_customer_id",
      "Stock Entry-selco_supplier_or_customer",
      "Stock Entry-selco_get_items_from_supplier_reference",
      "Stock Entry-selco_buyers_order_no",
      "Stock Entry-selco_dispatched_through",
      "Stock Entry-selco_dispatch_document_no",
      "Stock Entry-selco_suppliers_ref",
      "Stock Entry-selco_type_of_material",
      "Stock Entry-selco_being_dispatched_to",
      "Stock Entry-selco_inward_or_outward",
      "Stock Entry-selco_type_of_stock_entry",
      "Stock Entry-selco_branch",
      "Purchase Receipt-selco_purchase_receipt_item_print",
      "Purchase Order-workflow_state",
      "Material Request Item-selco_dispatched_quantity",
      "Material Request-workflow_state",
      "Material Request-selco_date",
      "Material Request-selco_material_request_type",
      "Issue-selco_complaint_received_date",
      "Warranty Claim-workflow_state",
      "Issue-workflow_state",
      "Issue-selco_customer_contact_number_landline",
      "Stock Reconciliation-selco_branch",
      "Item-selco_tally_code",
      "Sales Person-selco_show_in_daily_report",
      "Sales Person-selco_branch",
      "Sales Person-selco_designation",
      "Sales Person-selco_contact_number",
      "Warranty Claim-selco_complaint_number",
      "Warranty Claim-dc_number",
      "Warranty Claim-item_group",
      "Warranty Claim-selco_item_group",
      "Warranty Claim-selco_docket_date_godown_to_branch",
      "Warranty Claim-selco_docket_date_branch_to_godown",
      "Sales Order Item-gst_hsn_code",
      "Supplier Quotation Item-gst_hsn_code",
      "Print Settings-print_taxes_with_zero_amount",
      "Print Settings-compact_item_print",
      "Deleted Document-hub_sync_id",
      "Company-hub_sync_id",
      "Warranty Claim-cb11",
      "Warranty Claim-selco_docket_number_and_details_godown_to_branch",
      "Warranty Claim-selco_docket_number_and_details_branch_to_godown",
      "Warranty Claim-selco_courier_details",
      "Warranty Claim-selco_inverter_load",
      "Warranty Claim-selco_luminaries",
      "Warranty Claim-selco_load_details",
      "Warranty Claim-selco_dc_date_branch_to_godown",
      "Warranty Claim-cb1",
      "Warranty Claim-selco_dc_number_branch_to_godown",
      "Warranty Claim-selco_branch_to_godown_dc_details",
      "Warranty Claim-selco_fan_luminery_make",
      "Warranty Claim-selco_serial_number",
      "Warranty Claim-selco_capacity",
      "Warranty Claim-selco_fan_luminary_other_details",
      "Warranty Claim-selco_temperature_of_hot_water_in_collector_day_2",
      "Warranty Claim-selco_temperature_of_hot_water_in_tank_day_2",
      "Warranty Claim-selco_outside_temperature_day_2",
      "Warranty Claim-selco_oht_height",
      "Warranty Claim-selco_present_water_test_report_in_ppm",
      "Warranty Claim-selco_water_test_report_before_supplying_system",
      "Warranty Claim-selco_site_survey_done_before_supplying",
      "Warranty Claim-selco_source_of_water",
      "Warranty Claim-selcob8",
      "Warranty Claim-selco_temperature_of_hot_water_in_collector_day_1",
      "Warranty Claim-selco_temperature_of_hot_water_in_tank_day_1",
      "Warranty Claim-selco_outside_temperature_day_1",
      "Warranty Claim-selco_type_of_water_heater",
      "Warranty Claim-selco_water_heater_make",
      "Warranty Claim-selco_serial_no_of_collector",
      "Warranty Claim-selco_serial_no_of__storage_tank",
      "Warranty Claim-selco_water_heater_name",
      "Warranty Claim-selco_water_heater_capacity",
      "Warranty Claim-selco_water_heater_details",
      "Warranty Claim-selco_inverter_within_warranty",
      "Warranty Claim-selco_inverter_make",
      "Warranty Claim-selco_inverter_capacity",
      "Warranty Claim-selcob9",
      "Warranty Claim-selco_inverter_serial_number",
      "Warranty Claim-selco_inverter_name",
      "Warranty Claim-selco_inverter_details",
      "Warranty Claim-selco_cell_no_6",
      "Warranty Claim-selco_cell_no_5",
      "Warranty Claim-selco_cell_no_4",
      "Warranty Claim-selco_battery_within_warranty",
      "Warranty Claim-selco_battery_supplier",
      "Warranty Claim-selcocb7",
      "Warranty Claim-selco_battery_voltage",
      "Warranty Claim-selco_cell_no_3",
      "Warranty Claim-selco_cell_no_2",
      "Warranty Claim-selco_cell_no_1",
      "Warranty Claim-selco_battery_serial_number",
      "Warranty Claim-selco_battery_name",
      "Warranty Claim-selco_battery_capacity",
      "Warranty Claim-selco_battery_details_",
      "Warranty Claim-within_warranty",
      "Warranty Claim-selcob6",
      "Warranty Claim-selco_panel_make",
      "Warranty Claim-selco_panel_serial_number",
      "Warranty Claim-selco_panel_details",
      "Warranty Claim-selco_panel_name",
      "Warranty Claim-selco_panel_capacity",
      "Warranty Claim-selco_technical_information",
      "Warranty Claim-selco_within_warranty",
      "Warranty Claim-selco_supplier",
      "Warranty Claim-selco_item_serial_no",
      "Warranty Claim-cb2",
      "Warranty Claim-selco_item_description",
      "Warranty Claim-selco_item_name",
      "Warranty Claim-selco_item_code",
      "Warranty Claim-component_details",
      "Warranty Claim-selco_charge_regulator_fan_luminary_others",
      "Warranty Claim-selcob5",
      "Warranty Claim-selco_water_heater",
      "Warranty Claim-selcob4",
      "Warranty Claim-selco_inverter",
      "Warranty Claim-selcob3",
      "Warranty Claim-selco_battery",
      "Warranty Claim-selcob2",
      "Warranty Claim-selco_panel",
      "Warranty Claim-component",
      "Warranty Claim-selco_fsr_date",
      "Warranty Claim-selco_warranty_card_date",
      "Warranty Claim-selco_dc_date",
      "Warranty Claim-selco_ics_date",
      "Warranty Claim-selco_invoice_date",
      "Warranty Claim-selco2",
      "Warranty Claim-selco_latest_fsr_number",
      "Warranty Claim-selco_warranty_card_number",
      "Warranty Claim-selco_dc_number",
      "Warranty Claim-selco_ics_number",
      "Warranty Claim-selco_invoice_number",
      "Warranty Claim-selco1",
      "Warranty Claim-selco_godown_email_id",
      "Warranty Claim-selco_senior_service_manager_email_id",
      "Warranty Claim-selco_customer_full_name",
      "Warranty Claim-selco_branch",
      "Warranty Claim-selco_remarks_by_godown",
      "Warranty Claim-selco_detailed_description_of_complaint",
      "Address-selco_district",
      "Address-selco_address_count",
      "Address-selco_branch",
      "Material Request Item-selco_rate",
      "Material Request Item-selco_quantity",
      "Material Request-selco_items_print",
      "Material Request-sb1",
      "Material Request-selco_is_it_eshala_ibm",
      "Material Request-selco_dispatched_time",
      "Material Request-selco_approved_time",
      "Material Request-selco_present_limit",
      "Material Request-selco_branch_credit_limit",
      "Material Request-selco_total_of_stock_and_debtors",
      "Material Request-selco_default_warehouse",
      "Material Request-selco_stock_value",
      "Material Request-selco_present_debtors",
      "Material Request-selco_advance",
      "Material Request-selco_ibm_value",
      "Material Request-selco_ibm_type",
      "Material Request-selco_agms_email_id",
      "Material Request-selco_godown_email_id",
      "Material Request-selco_senior_sales_manager_email_id",
      "Material Request-selco_dc_date",
      "Material Request-selco_dc_number",
      "Material Request-selco_expected_dispatch_date",
      "Material Request-selco_godown_oa_comments",
      "Material Request-selco_senior_manager_comments",
      "Material Request-selco_branch",
      "Material Request-selco_description",
      "Material Request-selco_sales_through",
      "Material Request-selco_order_acknowledgement_no_",
      "Quotation-selco_sales_person",
      "Quotation-selco_branch",
      "Opportunity-selco_pricing_urgency_level",
      "Opportunity-selco_customer_interest_level",
      "Opportunity-selco_branch",
      "Opportunity-selco_date_",
      "Lead-selco_product_type",
      "Lead-selco_area",
      "Lead-selco_project_enquiry_details",
      "Lead-selco_conversion_index",
      "Lead-selco_approximate_cost",
      "Lead-po",
      "Lead-selco_address_and_marks",
      "Lead-selco_type_of_sales",
      "Lead-selco_business_associate",
      "Lead-selco_customer_contact_number__mobile_2_landline",
      "Lead-selco_sales_person_project_manager",
      "Lead-selco_product_interested",
      "Lead-selco_project_enquiry",
      "Lead-selco_electrified_or_unelectrified",
      "Lead-selco_customer_contact_number__mobile_1",
      "Lead-selco_branch",
      "Lead-selco_date",
      "Journal Entry-selco_sales_invoice",
      "Journal Entry-sales_invoice_reference",
      "Sales Invoice-selco_type_of_financing_institute",
      "Sales Invoice-selco_purpose",
      "Sales Invoice-selco_type_of_invoice",
      "Sales Invoice-selco_sales_account",
      "Sales Invoice-selco_service_bill_no",
      "Delivery Note-amount_in_print",
      "Delivery Note-rate_in_print",
      "Delivery Note-selco_quantity_in_print_",
      "Delivery Note-selco_system_name_in_print",
      "Delivery Note-selco_terms_of_delivery",
      "Delivery Note-selco_sales_person",
      "Delivery Note-selco_branch",
      "Sales Invoice-selco_customer_tin_number",
      "Sales Invoice-selco_customer_contact_number",
      "Payment Entry-pg",
      "Payment Entry-received_amount_with_deduction",
      "Payment Entry-selco_narration",
      "Payment Entry-fg",
      "Payment Entry-selco_financing_institution_branch",
      "Payment Entry-selco_financing_institution",
      "Payment Entry-op",
      "Payment Entry-selco_cheque__reference_bank",
      "Payment Entry-selco_cheque_issuing_bank",
      "Payment Entry-selco_financed",
      "Payment Entry-selco_o_a_date",
      "Payment Entry-selco_o_a_no",
      "Payment Entry-selco_amount_credited_to_platinum_account",
      "Payment Entry-selco_money_received_by",
      "Payment Entry-selco_recipient_address",
      "Payment Entry-selco_recipient_address_link",
      "Payment Entry-selco_branch",
      "Purchase Invoice-selco_supplier_invoice_date",
      "Purchase Invoice-selco_godown",
      "Purchase Invoice-selco_supplier_invoice_number",
      "Purchase Receipt-selco_list_of_po_date",
      "Purchase Receipt-selco_list_of_po",
      "Purchase Receipt-remark",
      "Purchase Receipt-we",
      "Purchase Receipt-selco_supplier_invoice_date",
      "Purchase Receipt-selco_supplier_invoice_number",
      "Purchase Receipt-selco_godown",
      "Purchase Order-selco_terms_of_payment",
      "Purchase Order-selco_balance_details_currency",
      "Purchase Order-selco_advance_details_currency",
      "Purchase Order-selco_godown_email",
      "Purchase Order-selco_godown_address_details",
      "Purchase Order-selco_godown_address",
      "Purchase Order-selco_pdc_no_of_days",
      "Purchase Order-selco_advance_percentage_1",
      "Purchase Order-selco_terms_of_delivery",
      "Purchase Order-selco_dispatch_through",
      "Purchase Order-selco_supplier_gstin",
      "Purchase Order-selco_supplier_vat_tin",
      "Supplier-selco_supplier_ifsc_code",
      "Supplier-selco_supplier_account_number",
      "Supplier-selco_supplier_bank_address",
      "Supplier-selco_supplier_bank_name",
      "Supplier-selco_terms_and_conditions",
      "Supplier-selco_gstin",
      "Supplier-selco_suppliers_vat_tin",
      "Terms and Conditions-selling",
      "Terms and Conditions-buying_",
      "Purchase Order Item-gst_hsn_code",
      "Sales Invoice Item-gst_hsn_code",
      "Purchase Receipt Item-gst_hsn_code",
      "Address-gst_state_number",
      "Address-gst_state",
      "Address-gstin",
      "Sales Invoice-ecommerce_gstin",
      "Sales Invoice-export_type",
      "Sales Invoice-invoice_type",
      "Sales Invoice-gst_col_break",
      "Sales Invoice-reverse_charge",
      "Sales Invoice-invoice_copy",
      "Sales Invoice-gst_section",
      "Sales Invoice-company_gstin",
      "Sales Invoice-place_of_supply",
      "Sales Invoice-customer_gstin",
      "Sales Invoice-billing_address_gstin",
      "Delivery Note-company_gstin",
      "Delivery Note-place_of_supply",
      "Delivery Note-customer_gstin",
      "Delivery Note-billing_address_gstin",
      "Purchase Invoice-ecommerce_gstin",
      "Purchase Invoice-export_type",
      "Purchase Invoice-invoice_type",
      "Purchase Invoice-gst_col_break",
      "Purchase Invoice-reverse_charge",
      "Purchase Invoice-invoice_copy",
      "Purchase Invoice-gst_section",
      "Purchase Invoice-company_gstin",
      "Purchase Invoice-supplier_gstin",
      "Quotation Item-gst_hsn_code",
      "Purchase Invoice Item-gst_hsn_code",
      "Delivery Note Item-gst_hsn_code",
      "Item-gst_hsn_code",
      "Warehouse-parent_account",
      "Branch-nm",
      "Branch-selco_cost_center",
      "Branch-accounting_details",
      "Branch-selco_warehouse",
      "Branch-lp",
      "Branch-selco_git_warehouse",
      "Branch-stock_details",
      "Branch-pl",
      "Branch-crm_",
      "Branch-selco_senior_manager",
      "Branch-selco_service_branch_email_id",
      "Branch-selco_godown_email_id",
      "Branch-selco_agm_email_id",
      "Branch-sd",
      "Branch-selco_branch_credit_limit",
      "Branch-selco_service_manager_email_id",
      "Branch-selco_senior_sales_manager_email_id",
      "Branch-selco_branch_email_id",
      "Issue-selco_service_record",
      "Issue-selco_service_record_details",
      "Issue-selco_sbm_remarks",
      "Issue-selco_sbm_name_if_involved",
      "Issue-selco_complaint_closed_date",
      "Issue-selco_service_charges_collected",
      "Issue-selco_service_record_date_2",
      "Issue-selco_service_record_date_1",
      "Issue-selco_faulty_component_vendor",
      "Issue-selco_service_person_name",
      "Issue-selco_complaint_handled_by_cse",
      "Issue-selco_ics_date",
      "Issue-c",
      "Issue-selco_service_area",
      "Issue-selco_closing",
      "Issue-selco_google_spreadsheet_number",
      "Issue-selco_sms_counter_1",
      "Issue-selco_complaint_pending_with",
      "Issue-selco_special_budget",
      "Issue-cbnlk",
      "Issue-selco_remarks",
      "Issue-selco_input_buy_csd_closing",
      "Issue-selco_service_record_date",
      "Issue-selco_faulty_component_vendor_name",
      "Issue-selco_complaint_handled_by_cse_or_sr_cse",
      "Issue-selco_branch_remarks",
      "Issue-selco_receipt_number",
      "Issue-selco_component_charges",
      "Issue-selco_service_record_number_2",
      "Issue-selco_service_record_number_1",
      "Issue-selco_faulty_complaint",
      "Issue-selco_category_of_complaint",
      "Issue-selco_ics_number",
      "Issue-selco_to_be_input_by_branch_or__sbm",
      "Issue-selco_warranty_claim_number",
      "Issue-selco_capacity",
      "Issue-selco_type_of_system",
      "Issue-selco_warranty_aplicable",
      "Issue-selco_complaint_priority",
      "Issue-selco_add_address",
      "Issue-selco_customer_address",
      "Issue-selco_customer_contact_number",
      "Issue-selco_customer_full_name",
      "Issue-selco_customer_id",
      "Issue-selco_warranty_claim_format",
      "Issue-selco_detail_address",
      "Issue-selco_description_of_complaint",
      "Issue-selco_service_branch_email_id",
      "Issue-selco_branch_email_id",
      "Issue-selco_service_area_name",
      "Issue-selco_branch",
      "Customer-selco_landline_mobile_2",
      "Customer-selco_customer_tin_number",
      "Customer-selco_electrification_status",
      "Customer-selco_customer_contact_number",
      "Customer-selco_gender",
      "Customer-selco_branch",
      "Customer-status", "Material Request-selco_eshala_proposal_number", "Material Request-selco_content_dispatched", "Purchase Order-selco_delivery_address"]],
    ]
  },
  {"dt": "Print Format",
   "filters": 
     [["name", "in", [
      "SELCO IBM",
      "SELCO Stock Entry",
      "SELCO - IBM",
      "GST DC SELCO",
      "SELCO GST Sales Invoice",
      "Receipt SELCO",
      "SELCO Receipt",
      "SELCO GRN/DC/REJO",
      "GRN/DC",
      "Godown DC",
      "SELCO",
      "SELCO MRN OLD",
      "SELCO MRN With Rate",
      "SELCO MRN",
      "SELCO New MRN",
      "SELCO PO - With Line Break",
      "SELCO PO",
      "SELCO PO - With Letter Head",
      "SELCO PO GST",
      "Delivery Note Test",
      "SELCO GST PO",
      "Sales Invoice-4 Copies(Karnataka)",
      "Sales Invoice-4 Copies(Munger)",
      "Sales Invoice-4 Copies(Kasargod)",
      "Sales Invoice-4 Copies(Solapur)",
      "Sales Invoice-4 Copies(TN)",
      "test",
      "Test 1",
      "Delivery Note SELCO(Kasargod)",
      "Delivery Note SELCO(Munger)",
      "Delivery Note SELCO(TN)",
      "Delivery Note SELCO(Solapur)",
      "SELCO PO GST - With Letterhead",
      "Sales Invoice-4 Copies",
      "Detailed Tax Invoice",
      "Tax Invoice",
      "SELCO Sales Invoice",
      "Delivery Note SELCO",
      "SELCO Packing Slip",
      "SELCO Receipt - 3 Copies",
      "Warranty Claim Format",
      "SELCO IBM",
      "Simplified Tax Invoice",
      "SELCO Receipt - 2 Copies",
      "GST POS Invoice",
      "Point of Sale",
      "GST Tax Invoice",
      "Consultation Print",
      "Lab Test Print",
      "Sample ID Print",
      "Salary Slip Standard",
      "Salary Slip based on Timesheet",
      "Drop Shipping Format",
      "Offer Letter",
      "Payment Receipt Voucher",
      "Credit Note",
      "Cheque Printing Format",
      "POS Invoice", "SELCO New MRN"
        ]]]},

  {"dt": "Property Setter",
   "filters": 
     [["name", "in", [
      "Delivery Note-apply_discount_on-default",
      "Delivery Note-apply_discount_on-read_only",
      "Branch-selco_receipt_note_naming_series-width",
      "Purchase Receipt-naming_series-options",
      "Issue-raised_by-width",
      "Purchase Order-naming_series-options",
      "Journal Entry-naming_series-options",
      "Journal Entry-naming_series-default",
      "Customer-customer_name-width",
      "Branch-selco_branch_email_id-width",
      "Issue-naming_series-options",
      "Payment Entry-naming_series-options",
      "Branch-selco_receipt_naming_series-width",
      "Service Person-selco_service_or_installation-options",
      "Sales Invoice-apply_discount_on-default",
      "Sales Invoice-apply_discount_on-read_only",
      "User-last_active-width",
      "Stock Entry Detail-actual_qty-width",
      "Stock Entry Detail-basic_rate-in_list_view",
      "Stock Entry Detail-amount-in_list_view",
      "Warehouse-warehouse_name-width",
      "Payment Entry-default_print_format",
      "Stock Entry-default_print_format",
      "Sales Invoice-sales_team-reqd",
      "Purchase Order-default_print_format",
      "Sales Invoice-remarks-print_hide",
      "Customer-naming_series-hidden",
      "Address-state-options",
      "Address-state-fieldtype",
      "Stock Entry-from_warehouse-width",
      "Stock Entry Detail-s_warehouse-width",
      "Stock Entry-selco_inward_or_outward-width",
      "Sales Invoice-default_print_format",
      "Sales Team-sales_person-width",
      "User-email-width",
      "Payment Entry-title_field",
      "User Permission-for_value-width",
      "Warehouse-selco_address-width",
      "Customer-naming_series-options",
      "Stock Entry-title_field",
      "Stock Entry Detail-item_name-in_list_view",
      "Stock Entry Detail-t_warehouse-in_list_view",
      "Stock Entry Detail-s_warehouse-in_list_view",
      "Stock Entry Detail-barcode-hidden",
      "Sales Order-tax_id-print_hide",
      "Sales Order-tax_id-hidden",
      "Supplier Quotation-rounded_total-print_hide",
      "Supplier Quotation-rounded_total-hidden",
      "Supplier Quotation-base_rounded_total-print_hide",
      "Supplier Quotation-base_rounded_total-hidden",
      "Sales Order-payment_schedule-print_hide",
      "Sales Order-due_date-print_hide",
      "Issue-response-hidden",
      "Bank Payment-subscription_section-hidden",
      "Bank Payment-addtional_info-hidden",
      "Bank Payment-printing_settings-hidden",
      "Bank Payment-difference-hidden",
      "Bank Payment-total_credit-hidden",
      "Bank Payment-total_debit-hidden",
      "Bank Payment-voucher_type-default",
      "Bank Payment-voucher_type-options",
      "Sales Invoice-terms_section_break-hidden",
      "Sales Invoice-ignore_pricing_rule-hidden",
      "Sales Invoice-territory-hidden",
      "Sales Invoice-contact_person-hidden",
      "Sales Invoice-subscription_section-hidden",
      "Sales Invoice-sales_team_section_break-hidden",
      "Sales Invoice-more_information-hidden",
      "Sales Invoice-edit_printing_settings-hidden",
      "Sales Invoice-payment_schedule_section-hidden",
      "Sales Invoice-shipping_rule-hidden",
      "Sales Invoice-total_net_weight-hidden",
      "Sales Invoice-time_sheet_list-hidden",
      "Sales Invoice-update_stock-hidden",
      "Sales Invoice-due_date-hidden",
      "Sales Invoice-set_posting_time-hidden",
      "Sales Invoice-is_pos-hidden",
      "Sales Invoice-project-hidden",
      "Purchase Invoice-payments_section-hidden",
      "Purchase Invoice-is_paid-hidden",
      "Purchase Invoice-printing_settings-hidden",
      "Purchase Receipt Item-item_weight_details-hidden",
      "Purchase Invoice-disable_rounded_total-default",
      "Purchase Invoice-disable_rounded_total-hidden",
      "Purchase Order Item-base_net_amount-hidden",
      "Purchase Order Item-base_net_rate-hidden",
      "Purchase Order Item-item_weight_details-hidden",
      "Purchase Order Item-item_name-in_list_view",
      "Purchase Order Item-schedule_date-in_list_view",
      "Purchase Invoice Item-item_weight_details-hidden",
      "Purchase Invoice-raw_materials_supplied-hidden",
      "Purchase Invoice-shipping_rule-hidden",
      "Purchase Invoice-update_stock-hidden",
      "Purchase Receipt-base_total_taxes_and_charges-hidden",
      "Purchase Receipt-base_taxes_and_charges_deducted-hidden",
      "Purchase Receipt-base_taxes_and_charges_added-hidden",
      "Purchase Receipt-shipping_rule-hidden",
      "Purchase Receipt-raw_material_details-hidden",
      "Purchase Receipt-printing_settings-hidden",
      "Purchase Order-total_taxes_and_charges-hidden",
      "Purchase Order-base_taxes_and_charges_deducted-hidden",
      "Purchase Order-base_taxes_and_charges_added-hidden",
      "Purchase Order-base_net_total-hidden",
      "Purchase Order-base_total-hidden",
      "Purchase Order-link_to_mrs-hidden",
      "Purchase Order-ignore_pricing_rule-hidden",
      "Purchase Order-plc_conversion_rate-hidden",
      "Purchase Order-price_list_currency-hidden",
      "Purchase Order-conversion_rate-default",
      "Purchase Order-conversion_rate-hidden",
      "Purchase Order-currency-default",
      "Purchase Order-currency-hidden",
      "Purchase Invoice-payment_schedule_section-hidden",
      "Purchase Receipt-bill_date-hidden",
      "Purchase Receipt-bill_no-hidden",
      "Purchase Order-shipping_rule-hidden",
      "Issue-issue_type-hidden",
      "Supplier-supplier_name-in_standard_filter",
      "Purchase Receipt-default_print_format",
      "Purchase Order-more_info-hidden",
      "Purchase Order-more_info-collapsible",
      "Purchase Order-column_break5-hidden",
      "Purchase Order-column_break5-collapsible",
      "Purchase Order-supplied_items_section-hidden",
      "Purchase Order-payment_schedule_section-hidden",
      "Bank Payment-naming_series-options",
      "Contra Entry-naming_series-options",
      "Employee-naming_series-options",
      "Purchase Order-get_items_from_open_material_requests-hidden",
      "Purchase Order-naming_series-read_only",
      "Branch-quick_entry",
      "Journal Entry-voucher_type-options",
      "Cash Payment Entry-voucher_type-default",
      "Cash Payment Entry-voucher_type-hidden",
      "Cash Payment Entry-voucher_type-reqd",
      "Address-address_title-bold",
      "Address-track_changes",
      "Address-quick_entry",
      "Stock Entry-project-hidden",
      "Stock Entry-more_info-collapsible",
      "Stock Entry-printing_settings-hidden",
      "Stock Entry-additional_costs_section-hidden",
      "Stock Entry-sb1-depends_on",
      "Stock Entry-from_bom-depends_on",
      "Stock Entry-purpose-options",
      "Stock Entry-purpose-default",
      "Stock Entry-to_warehouse-read_only",
      "Stock Entry-from_bom-default",
      "Stock Entry-purpose-read_only",
      "Stock Entry-naming_series-default",
      "Stock Entry-naming_series-read_only",
      "Stock Entry-naming_series-depends_on",
      "Stock Entry-naming_series-options",
      "Payment Entry-party_balance-depends_on",
      "Purchase Invoice-write_off-hidden",
      "Purchase Invoice-supplier_invoice_details-hidden",
      "Purchase Invoice-supplier_invoice_details-collapsible",
      "Purchase Invoice-subscription_section-hidden",
      "Purchase Order-company-hidden",
      "Purchase Order-company-reqd",
      "Purchase Order-sec_tax_breakup-hidden",
      "Purchase Order-sec_tax_breakup-collapsible",
      "Purchase Order-section_addresses-hidden",
      "Purchase Order-section_addresses-collapsible",
      "Purchase Order-naming_series-default",
      "Purchase Order-discount_section-hidden",
      "Purchase Order-taxes_and_charges-reqd",
      "Purchase Order-subscription_section-hidden",
      "Purchase Order-schedule_date-default",
      "Purchase Order-schedule_date-hidden",
      "Material Request-schedule_date-default",
      "Material Request-schedule_date-hidden",
      "Material Request-material_request_type-hidden",
      "Material Request-material_request_type-reqd",
      "Warranty Claim-complaint-reqd",
      "Supplier-language-hidden",
      "Supplier-tax_id-hidden",
      "Supplier-quick_entry",
      "Address-is_primary_address-default",
      "Issue-title_field",
      "Customer-naming_series-read_only",
      "Customer-naming_series-reqd",
      "Service Person-quick_entry",
      "Warehouse Type-title_field",
      "Warehouse Type-delete_purchase_receipt-hidden",
      "Warranty Claim-status-hidden",
      "Warranty Claim-status-reqd",
      "Warranty Claim-status-in_list_view",
      "Warranty Claim-customer-read_only",
      "Warranty Claim-customer-reqd",
      "Warranty Claim-serial_no-hidden",
      "Warranty Claim-complaint_date-label",
      "Warranty Claim-more_info-hidden",
      "Warranty Claim-more_info-collapsible",
      "Warranty Claim-issue_details-hidden",
      "Warranty Claim-resolution_section-hidden",
      "Warranty Claim-section_break_7-hidden",
      "Employee-employee_number-hidden",
      "Employee-employee_number-reqd",
      "Employee-naming_series-reqd",
      "Employee-naming_series-hidden",
      "Supplier Quotation-in_words-print_hide",
      "Supplier Quotation-in_words-hidden",
      "Sales Order-in_words-print_hide",
      "Sales Order-in_words-hidden",
      "Sales Order-rounded_total-print_hide",
      "Sales Order-rounded_total-hidden",
      "Sales Order-base_rounded_total-print_hide",
      "Sales Order-base_rounded_total-hidden",
      "Warranty Claim-section_break_7-label",
      "Warranty Claim-naming_series-hidden",
      "Warranty Claim-naming_series-reqd",
      "Material Request-terms_section_break-hidden",
      "Material Request-terms_section_break-collapsible",
      "Material Request-title_field",
      "Material Request-printing_details-hidden",
      "Material Request-more_info-hidden",
      "Material Request Item-item_name-in_list_view",
      "Material Request Item-schedule_date-reqd",
      "Material Request Item-schedule_date-in_list_view",
      "Material Request Item-warehouse-in_list_view",
      "Material Request-material_request_type-options",
      "Material Request-material_request_type-in_list_view",
      "Material Request-naming_series-options",
      "Material Request-naming_series-read_only",
      "Quotation-naming_series-in_list_view",
      "Quotation-more_info-hidden",
      "Quotation-taxes_and_charges-reqd",
      "Quotation-order_type-hidden",
      "Quotation-order_type-reqd",
      "Quotation-valid_till-hidden",
      "Quotation-naming_series-options",
      "Quotation-naming_series-read_only",
      "Opportunity-enquiry_type-hidden",
      "Opportunity-enquiry_type-reqd",
      "Opportunity-enquiry_type-in_list_view",
      "Opportunity-naming_series-options",
      "Opportunity-naming_series-read_only",
      "Lead-contact_info-hidden",
      "Lead-more_info-hidden",
      "Lead-section_break_12-hidden",
      "Lead-source-reqd",
      "Lead-email_id-label",
      "Lead-lead_name-label",
      "Lead-company_name-hidden",
      "Lead-gender-hidden",
      "Lead-naming_series-options",
      "Lead-naming_series-default",
      "Lead-naming_series-read_only",
      "Lead-naming_series-depends_on",
      "Journal Entry-naming_series-read_only",
      "Delivery Note-naming_series-options",
      "Delivery Note-naming_series-read_only",
      "Delivery Note-apply_discount_on-read_only",
      "Delivery Note-apply_discount_on-default",
      "Sales Person-employee-reqd",
      "Sales Invoice-naming_series-options",
      "Sales Invoice-naming_series-bold",
      "Sales Invoice-naming_series-read_only",
      "Sales Invoice-naming_series-reqd",
      "Payment Entry-section_break_12-label",
      "Payment Entry-reference_no-label",
      "Payment Entry-transaction_references-label",
      "Payment Entry-mode_of_payment-hidden",
      "Payment Entry-naming_series-hidden",
      "Payment Entry-naming_series-reqd",
      "Payment Entry-naming_series-label",
      "Purchase Invoice-posting_time-hidden",
      "Purchase Receipt-taxes_and_charges-reqd",
      "Purchase Receipt-naming_series-default",
      "Purchase Receipt-naming_series-read_only",
      "Purchase Receipt-supplier_delivery_note-hidden",
      "Purchase Invoice-naming_series-options",
      "Purchase Invoice-naming_series-default",
      "Purchase Order-column_break1-label",
      "Purchase Order-shipping_address-hidden",
      "Purchase Order-is_subcontracted-hidden",
      "Item-barcode-hidden",
      "Purchase Order-column_break1-hidden",
      "Sales Invoice Item-barcode-hidden",
      "Purchase Receipt Item-barcode-hidden",
      "Stock Reconciliation Item-barcode-hidden",
      "Delivery Note Item-barcode-hidden",
      "Item-item_code-reqd",
      "Item-item_code-hidden",
      "Item-naming_series-hidden",
      "Item-naming_series-reqd",
      "Supplier-naming_series-hidden",
      "Supplier-naming_series-reqd",
      "Delivery Note-tax_id-print_hide",
      "Delivery Note-tax_id-hidden",
      "Sales Invoice-tax_id-print_hide",
      "Sales Invoice-tax_id-hidden",
      "Purchase Receipt-in_words-print_hide",
      "Purchase Receipt-in_words-hidden",
      "Purchase Invoice-in_words-print_hide",
      "Purchase Invoice-in_words-hidden",
      "Purchase Order-in_words-print_hide",
      "Purchase Order-in_words-hidden",
      "Delivery Note-in_words-print_hide",
      "Delivery Note-in_words-hidden",
      "Sales Invoice-in_words-print_hide",
      "Sales Invoice-in_words-hidden",
      "Quotation-in_words-print_hide",
      "Quotation-in_words-hidden",
      "Delivery Note-rounded_total-print_hide",
      "Delivery Note-rounded_total-hidden",
      "Delivery Note-base_rounded_total-print_hide",
      "Delivery Note-base_rounded_total-hidden",
      "Sales Invoice-rounded_total-print_hide",
      "Sales Invoice-rounded_total-hidden",
      "Sales Invoice-base_rounded_total-print_hide",
      "Sales Invoice-base_rounded_total-hidden",
      "Quotation-rounded_total-print_hide",
      "Quotation-rounded_total-hidden",
      "Quotation-base_rounded_total-print_hide",
      "Quotation-base_rounded_total-hidden",
      "Warehouse-column_break_4-label",
      "Issue-section_break_19-hidden",
      "Issue-additional_info-hidden",
      "Issue-section_break_7-hidden",
      "Issue-subject_section-label",
      "Issue-raised_by-hidden",
      "Issue-subject-hidden",
      "Issue-subject-reqd",
      "Issue-status-hidden",
      "Issue-naming_series-read_only",
      "Issue-customer-hidden",
      "Issue-quick_entry",
      "Customer-is_frozen-hidden",
      "Customer-customer_type-hidden",
      "Customer-more_info-hidden",
      "Customer-credit_limit_section-hidden",
      "Customer-gender-hidden",
      "Customer-disabled-hidden",
      "Customer-sales_team_section-hidden",
      "Customer-sales_team_section_break-hidden",
      "Customer-column_break1-hidden",
      "Customer-column_break_14-hidden",
      "Customer-currency_and_price_list-hidden",
      "Customer-lead_name-hidden",
      "Customer-tax_id-hidden",
      "Customer-territory-in_list_view",
      "Customer-salutation-hidden",
      "Customer-naming_series-default",
      "Customer-customer_type-options",
      "Customer-customer_type-reqd",
      "Customer-salutation-label",
      "Customer-salutation-depends_on"
  ]]]},
    {"dt": "Report",
     "filters": 
       [["name", "in", [
      "Service Calls List"
      "Item Balance (Simple)",
      "Final Assessment Grades",
      "GSTR-2",
      "Manipal Godown Warranty Dispatch Pending - Batteries",
      "Bangalore Godown Warranty Dispatch Pending - Batteries",
      "palani Report",
      "Warranty Claim Dispatch Pending -All Godowns",
      "Dharwad Godown Warranty Dispatch Pending - Batteries",
      "Manipal Godown Warranty Dispatch Pending",
      "Bangalore Godown Warranty Dispatch Pending - All Items",
      "GSTR-1",
      "List Of POs To Be Approved By Ops",
      "Requested Items To Be Transferred - SELCO Custom",
      "Customer Addresses And Contacts",
      "Supplier Addresses and Contacts",
      "Supplier With Address",
      "Item Price Stock",
      "Assessment Plan Status",
      "Purchase Order Items To Be Received - SELCO Format",
      "Purchase Order Items To Be Received TEST",
      "Purchase Order Items To Be Received - SELCO",
      "PO Test",
      "Pending IBM Materials - Interstate",
      "Pending IBM Materials - Manipal Godown",
      "Pending IBM Materials - Bangalore Godown",
      "IBM Materials - Stationary",
      "Pending IBM Materials - Projects IBM",
      "Pending IBM Materials - Dharwad Godown",
      "Pending IBM Materials - Item Wise",
      "IBM's Pending For More Than 5 Days - Approved Time",
      "IBM's Pending For More Than 5 Days",
      "Livelihood Project IBM",
      "eShala IBMs",
      "Livelihood IBMs",
      "Complaint Register - Service Branchwise",
      "CSE Service Calls",
      "Complaint Rejected By CSD",
      "Complaint Budget - Service Branch Wise",
      "Open Complaint Details - Other than Warranty Claim",
      "Open Complaint Details - With Counter",
      "Open Complaint Details Including Warranty Claim Details-With Counter",
      "Cases Open For More Than 5 Days",
      "Complaint registered and closed in the same day",
      "Closed Complaint Details - With Counter",
      "Issue List All",
      "Summary Of Open Complaints - Branchwise",
      "Customer Details",
      "Complaint Register",
      "Closed Complaint Details - Closed Without SR",
      "1.Daily Complaint Received Report",
      "Palani Report 1",
      "Dharwad Godown Warranty Dispatch Pending - All Items",
      "Bangalore Godown Warranty Dispatch Pending",
      "Manipal Godown Warranty Dispatch Pending - All Items",
      "Dharwad Godown Warranty Dispatch Pending",
      "Palani Report 2",
      "Complaints Lodged Today",
      "Summary Of Open Complaints",
      "Item Variant Details",
      "Ordered Items To Be Delivered",
      "Ordered Items To Be Billed",
      "Delivered Items To Be Billed",
      "Received Items To Be Billed",
      "Sales Payment Summary",
      "Asset Maintenance",
      "Student Fee Collection",
      "Lab Test Report",
      "GST Purchase Register",
      "GST Itemised Sales Register",
      "GST Itemised Purchase Register",
      "GST Sales Register",
      "Support Hour Distribution",
      "Total Stock Summary",
      "BOM Stock Report",
      "ToDo",
      "Course wise Assessment Report",
      "Lead Owner Efficiency",
      "Campaign Efficiency",
      "Addresses And Contacts",
      "Prospects Engaged But Not Converted",
      "Student and Guardian Contact Details",
      "Sales Partners Commission",
      "Accounts Receivable Summary",
      "Accounts Receivable",
      "Lead Details",
      "Project wise Stock Tracking",
      "BOM Search",
      "Bank Clearance Summary",
      "Bank Reconciliation Statement",
      "Batch-Wise Balance History",
      "Budget Variance Report",
      "Customer Acquisition and Loyalty",
      "Delivery Note Trends",
      "Employee Birthday",
      "Employee Leave Balance",
      "General Ledger",
      "Item Prices",
      "Item-wise Purchase Register",
      "Item-wise Sales Register",
      "Itemwise Recommended Reorder Level",
      "Monthly Attendance Sheet",
      "Payment Period Based On Invoice Date",
      "Permitted Documents For User",
      "Purchase Invoice Trends",
      "Purchase Order Trends",
      "Purchase Receipt Trends",
      "Purchase Register",
      "Quotation Trends",
      "Sales Invoice Trends",
      "Sales Order Trends",
      "Sales Person Target Variance Item Group-Wise",
      "Sales Register",
      "Stock Ageing",
      "Stock Ledger",
      "Stock Projected Qty",
      "Supplier-Wise Sales Analytics",
      "Territory Target Variance Item Group-Wise",
      "Balance Sheet",
      "Profit and Loss Statement",
      "Trial Balance",
      "Gross Profit",
      "Customer Credit Balance",
      "Accounts Payable Summary",
      "Requested Items To Be Ordered",
      "Production Orders in Progress",
      "Completed Production Orders",
      "Open Production Orders",
      "Stock Balance",
      "Available Stock for Packing Items",
      "Accounts Payable",
      "Trial Balance for Party",
      "Cash Flow",
      "Inactive Customers",
      "Item-wise Purchase History",
      "Item-wise Sales History",
      "Asset Depreciation Ledger",
      "Asset Depreciations and Balances",
      "Pending SO Items For Purchase Request",
      "Requested Items To Be Transferred",
      "Minutes to First Response for Issues",
      "Minutes to First Response for Opportunity",
      "Items To Be Requested",
      "Daily Timesheet Summary",
      "Material Requests for which Supplier Quotations are not created",
      "Employees working on a holiday",
      "Quoted Item Comparison",
      "Purchase Order Items To Be Received",
      "Profitability Analysis",
      "Sales Person-wise Transaction Summary",
      "Absent Student Report",
      "Student Monthly Attendance Sheet",
      "Student Batch-Wise Attendance",
      "Item-wise Price List Rate",
      "Serial No Service Contract Expiry",
      "Serial No Warranty Expiry",
      "Employee Information",
      "Document Share Report",
      "Item Shortage Report",
      "Issued Items Against Production Order",
      "Batch Item Expiry Status",
      "Purchase Order Items To Be Billed",
      "Unpaid Expense Claim",
      "Vehicle Expenses",
      "Production Order Stock Report",
      "Salary Register",
      "Feedback Ratings",
      "Serial No Status",
      "Maintenance Schedules", "Open Complaint Details - Mobile", "Open Complaint Details With Warranty Claim Including Supplier"
    ]]]},  
    {"dt": "Workflow"},
    {"dt": "Role"},
    {"dt": "Workflow State"},
    {"dt": "Workflow Action"}

]
'''